-- MySQL Script generated by MySQL Workbench
-- Wed Apr 23 07:19:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`attribute_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attribute_category_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_category_id` (
  `id` INT NOT NULL,
  `product_id` VARCHAR(45) NULL,
  `attribute_category_id` INT NULL,
  `attribute_type_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute_category`
    FOREIGN KEY (`attribute_category_id`)
    REFERENCES `mydb`.`attribute_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attribute_type`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `mydb`.`attribute_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `attribute_category_idx` ON `mydb`.`attribute_category_id` (`attribute_category_id` ASC) VISIBLE;

CREATE INDEX `attribute_type_idx` ON `mydb`.`attribute_category_id` (`attribute_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`attribute_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_type` (
  `id` INT NOT NULL,
  `name` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `id brand` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id brand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colour` (
  `id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `idproduct` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `brand_id` INT NULL,
  `product_category_id` INT NULL,
  `base_price` INT NULL,
  PRIMARY KEY (`idproduct`),
  CONSTRAINT `brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`id brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_category`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `mydb`.`product category` (`idproduct category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `brand_idx` ON `mydb`.`product` (`brand_id` ASC) VISIBLE;

CREATE INDEX `product_category_idx` ON `mydb`.`product` (`product_category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`product category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product category` (
  `idproduct category` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduct category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_attribute` (
  `id` INT NOT NULL,
  `product_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_image` (
  `id` INT NOT NULL,
  `product_id` INT NULL,
  `image_url` VARCHAR(45) NULL,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `product_idx` ON `mydb`.`product_image` (`product_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`product_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_item` (
  `id` INT NOT NULL,
  `product_variation_id` INT NULL,
  `size_option_id` INT NULL,
  `stock_quantity` VARCHAR(45) NULL,
  `price_override` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_variation`
    FOREIGN KEY (`product_variation_id`)
    REFERENCES `mydb`.`product_variation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `size_option`
    FOREIGN KEY (`size_option_id`)
    REFERENCES `mydb`.`size_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `product_variation_idx` ON `mydb`.`product_item` (`product_variation_id` ASC) VISIBLE;

CREATE INDEX `size_option_idx` ON `mydb`.`product_item` (`size_option_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`product_variation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_variation` (
  `id` INT NOT NULL,
  `product_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`size_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`size_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`size_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`size_option` (
  `id` INT NOT NULL,
  `product_variation_id` INT NULL,
  `size_optioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `size_category`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`size_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
